[package]
name = "stt_realtime"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61", features = [
    "Media_SpeechRecognition",
    "Media_Devices",
    "Devices_Enumeration",
    "Globalization",
    "Foundation",
    "Foundation_Collections",
    "Win32_System_Com",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
] }
eframe = "0.29"
egui = "0.29"
